[template]
src = "iptables.tmpl"
dest = "/usr/local/bin/iptables.pp"
prefix = "/%%PROJECT%%/%%ENVIRONMENT%%"
uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/IptablesAllowTCP",
    "/config/IptablesAllowUDP"
]

reload_cmd = "/usr/bin/puppet apply --modulepath /etc/puppet/modules /usr/local/bin/iptables.pp"
